### ISSUE TITLE
Use an enum

### ISSUE THREAD

**Issue by martinthomson** [w3c/mst-content-hint#16]
The potential set of values is probably bounded, but an enum at least helps with documentation.  The attribute can be DOMString still.

Also, I think that convention uses `DOMString?` for values that might be unset.  Alternatively, define something explicit rather than the empty string for the default.

**Comment by pbos** [comment]
This was part issue #14, and true before it. Since the enum in use depended on MST.kind (one for audio, one for video), we couldn't use enums straight off the bat (implementations would still have to implement the algorithm defined in text).

We did want this to behave like an enum though, and with discussion in #3 nullable enums were considered an anti-pattern. I'm not sure if this remains true when we're no longer using enums, but this "doesn't act" like a normal DOMString.

Intention not to use another default (than "" or null) was to permit if (mst.contentHint) checking by having a falsy value.

**Comment by domenic** [comment]
Right, @pbos has outlined the history here. We definitely want to use "" instead of null, as discussed in #3. So it's `DOMString`, not `DOMString?`.

The question is then whether using an enum has any benefits. And it does not, besides documentation. But the documentation in the spec on what the valid values are is very good already, so creating a useless enum that is not used by implementations and has no effect on the IDL does not buy us anything.

**Comment by martinthomson** [comment]
Well, I think that "" being falsy is a mis-feature in JS, but I'll keep quiet.
